import numpy as np
from qiskit import QuantumCircuit, transpile
from qiskit import Aer
from qiskit.visualization import plot_histogram
import matplotlib.pyplot as plt

def balanced_constant(counts):
    if '0' in counts.keys():
        print("La función es constante")
    else:
        print("La función es balanceada")

print("Función constante todos los qubits a 0")
simulator = Aer.get_backend('qasm_simulator')
circuit = QuantumCircuit(5, 5)
circuit.barrier()
circuit.i(0)
circuit.i(1)
circuit.i(2)
circuit.i(3)
circuit.i(4)
circuit.barrier()
circuit.measure([0,1,2,3], [3,2,1,0])
compiled_circuit = transpile(circuit, simulator)
job = simulator.run(compiled_circuit, shots=1000)
result = job.result()
counts = result.get_counts(circuit)
balanced_constant(counts)
print(circuit)
plot_histogram(counts)
plt.show()

print("Función Balanceada No 1 Cambia si el bit No 1 es 1")
simulator = Aer.get_backend('qasm_simulator')
circuit = QuantumCircuit(5, 5)
circuit.x(0)
circuit.barrier()
circuit.cx(0, 3)
circuit.barrier()
circuit.measure([0,1,2,3], [3,2,1,0])
compiled_circuit = transpile(circuit, simulator)
job = simulator.run(compiled_circuit, shots=1000)
result = job.result()
counts = result.get_counts(circuit)
balanced_constant(counts)
print(circuit)
plot_histogram(counts)
plt.show()

print("Función Balanceada No 2 Cambia si el bit No 2 es 1")
simulator = Aer.get_backend('qasm_simulator')
circuit = QuantumCircuit(5, 5)
circuit.barrier()
circuit.cx(1, 3)
circuit.barrier()
circuit.measure([0,1,2,3], [3,2,1,0])
compiled_circuit = transpile(circuit, simulator)
job = simulator.run(compiled_circuit, shots=1000)
result = job.result()
counts = result.get_counts(circuit)
balanced_constant(counts)
print(circuit)
plot_histogram(counts)
plt.show()

print("Función Balanceada No 3 Cambia si el bit No 3 es 1")
simulator = Aer.get_backend('qasm_simulator')
circuit = QuantumCircuit(5, 5)
circuit.barrier()
circuit.cx(2, 3)
circuit.barrier()
circuit.measure([0,1,2,3], [3,2,1,0])
compiled_circuit = transpile(circuit, simulator)
job = simulator.run(compiled_circuit, shots=1000)
result = job.result()
counts = result.get_counts(circuit)
balanced_constant(counts)
print(circuit)
plot_histogram(counts)
plt.show()